### ISSUE TITLE
Kommentar

### ISSUE THREAD

**Issue by sebseb7** [ransomletter/ransomletter.github.io#6]
Also die Forderung ist vergleichbar mit einer Forderung an Leute denen nachts unter vorgehaltener Waffe die Brieftasche abverlangt wird zu fordern nicht drauf einzugehen. So eine Forderung stellt sich leicht, wenn man selbst nicht betroffen ist.

Dass diese Forderung aus der IT Branche kommt, hat zudem noch den faden Beigeschmack dass vom eigenen Versagen abgelenkt werden soll.

**Comment by ransomletter** [comment]
Der Vergleich hinkt und die Forderung kommt nicht aus der IT-Branche sondern aus der Forschung.
